#GETTING STARTED WITH TENSORFLOW

In [ ]:
import tensorflow as tf

In [ ]:
print("version is",tf.__version__)

version is 2.15.0


#EAGER EXEC

In [ ]:
if tf.executing_eagerly():
  print("enabled")
else:
  print("disabled")

enabled


#GPU CHECK

In [ ]:
if tf.test.gpu_device_name():
  print(tf.test.gpu_device_name())

else:
  print("install GPU based req resources and tf")

/device:GPU:0


In [ ]:
!nvidia-smi

Wed Jan  3 07:39:49 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   54C    P0              28W /  70W |    103MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

#CONSTANT TENSORS

In [ ]:
ct=tf.constant([[1,2],[3,4]])

In [ ]:
ct

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

#VARIABLE TENSORS

In [ ]:
vt=tf.Variable([[5,6],[7,8]])

In [ ]:
vt

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[5, 6],
       [7, 8]], dtype=int32)>

#CONCAT

In [ ]:
row_concat=tf.concat(values=[ct,vt],axis=0)

In [ ]:
row_concat

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]], dtype=int32)>

In [ ]:
col_concat=tf.concat(values=[ct,vt],axis=1)

In [ ]:
col_concat

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[1, 2, 5, 6],
       [3, 4, 7, 8]], dtype=int32)>

#0,1... TENSORS

In [ ]:
zero=tf.zeros(shape=[2,2],dtype=tf.int32)

In [ ]:
zero

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[0, 0],
       [0, 0]], dtype=int32)>

In [ ]:
ones=tf.ones(shape=[3,4],dtype=tf.int32)

In [ ]:
ones

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int32)>

#TRANSPOSE

In [ ]:
tt=tf.transpose(ct)

In [ ]:
tt

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [2, 4]], dtype=int32)>

#TYPE CONVERSION

In [ ]:
tt_float=tf.cast(tt,tf.float32)

In [ ]:
tt_float

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 3.],
       [2., 4.]], dtype=float32)>

#TENSOR MULTI

In [ ]:
tm=tf.multiply(tt,ct) #direct mult

In [ ]:
tm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  6],
       [ 6, 16]], dtype=int32)>

In [ ]:
tmm=tf.matmul(tt,ct)

In [ ]:
tmm

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 14],
       [14, 20]], dtype=int32)>

#TENSOR DETERMINANT

In [ ]:
td=tf.linalg.det(tt_float)

In [ ]:
td

<tf.Tensor: shape=(), dtype=float32, numpy=-2.0>

#INVERSE

In [ ]:
inverse=tf.linalg.inv(tt_float)

In [ ]:
inverse

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2. ,  1.5],
       [ 1. , -0.5]], dtype=float32)>

#IDENTITY MATRIX

In [ ]:
identity=tf.eye(num_rows=2,num_columns=2,dtype=tf.int32)

In [ ]:
identity

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 0],
       [0, 1]], dtype=int32)>

#RESHAPING TENSOR

In [ ]:
rt=tf.reshape(tensor=inverse,shape=[4,1])

In [ ]:
rt

<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[-2. ],
       [ 1.5],
       [ 1. ],
       [-0.5]], dtype=float32)>

#NUMPY TO TENSOR

In [ ]:
import numpy as np
arr1=np.array([[2,2,3],[5,6,7]])
arr1

array([[2, 2, 3],
       [5, 6, 7]])

In [ ]:
tf.convert_to_tensor(arr1)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[2, 2, 3],
       [5, 6, 7]])>